# Problem: Even Fibonacci numbers
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


print_fibonacci = lambda do |*args|
  c = args[0] + args[1]
  print c
  print "\s"
  return args[1], c
end

a, b = 1, 2
sum = 2
puts "Please enter the limit for max number in fibanocci"
n = gets.chomp.to_i
print "#{a}\s#{b}\s"

loop do
  a,b= print_fibonacci.call(a,b)
  break if b >= n
  sum += b if b%2 == 0
end
puts "\nSum of even fibanocci numbers"
puts sum
